FROM node:20-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

#RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile
RUN pnpm install
RUN pnpm build

EXPOSE 3000

CMD [ "npx", "next", "start",  "--https", "--ssl-cert", "each-star.com_bundle.pem", "--ssl-key", "each-star.com.key"]
